# -*- coding: utf-8 -*-
"""app_Bollette

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132tjUbNxK4slv9mpo097anaQV_Q7GUEC

# COSTO BOLLETTE CASA DI SOPRA
"""

import streamlit as st


def consumo_utente(prezzo_unita, prezzo_fisso_mensile, unita_consumate, iva, partite):
    prezzo_fisso_mensile /= 2
    iva /= 2

    prezzo_consumo = prezzo_unita * unita_consumate

    totale = (prezzo_fisso_mensile + iva + prezzo_consumo + partite/2)

    return totale


st.title("Calcolo Consumo Utente")

prezzo_unita = st.number_input("Prezzo unità (€/Smc)", value=0.0)
prezzo_fisso = st.number_input("Quota fissa (€)", value=0.0)
unita = st.number_input("Unità consumate utente", value=0.0)
iva = st.number_input("IVA (€)", value=0.0)
partite = st.number_input("Altre partite (€)", value=0.0)

if st.button("Calcola"):
    risultato = consumo_utente(prezzo_unita, prezzo_fisso, unita, iva, partite)
    st.success(f"Totale: {risultato:.2f} €")
